all:
	ghc -O2 -Wall -fno-spec-constr-count -threaded --make dc

prod:
	ghc -O2 -Wall -Werror -fno-spec-constr-count -threaded --make dc

prof:
	ghc -rtsopts -prof -auto-all -O2 -v -Wall -Werror --make dc
	./dc +RTS -p

srclist:
	$(shell find -type f -regex ".*\.hs" > srclist)

clean:
	$(RM) dc
	find -type f -iregex ".+\.\(aux\|o\|hi\|hp\|mix\|ps\|tix\|html\)" -exec rm -v {} \;
